### ISSUE TITLE
Working documentation example missing

### ISSUE THREAD

**Issue by almereyda** [chpio/docker-cjdns#2]
In case users want to use this repository and associated image on Docker Hub for building a `cjdns` VPN, the instructions are currently very bare to the bones.

An introductory tutorial for connecting two peers, one server with static IP in the internet, probably with IPv4 forwarding, and a laptop client making use of such forward route, could be explained.

Right now I manage to create virtual bridges `ip -6 a` and routes `ip -6 r` with this container, but cannot ping the remote's IPv6 address from its `cjdroute.conf` nor receive log output about whether the remote connection has been successfully established, or not. Do I rather need to use `net: host` for this use case?

It appears the currently documented case is limited to inter-container networking, as in https://github.com/ipfs/infrastructure/issues/96#issue-109621759

**Comment by almereyda** [comment]
I am working from https://github.com/chpio/docker-cjdns/compare/master...ecobytes:master and provided all necessary SELinux exceptions to the cjdns binary.

**Comment by chpio** [comment]
i have no idea what you'r willing to do (tunneling ipv6/ipv4 over cjdns?!). actually this is just a repo for a cjdns-dockerfile nothing more, so i don't think im the one "in charge" writing tutorials for cjdns.
if you have questions about cjdns ask them on the cjdns repo, i guess the cjdns devs know a lot more about cjdns than i do.

> It appears the currently documented case is limited to inter-container networking

yes, i will add more.

**Comment by almereyda** [comment]
What I was trying to point out is that the a mere Dockerfile is not easily usable if there is no documentation that explains how to use it in the Docker Engine and Compose context, including virtual networking and the likes. As I am working on the scenario presented above, I could try to provide these docs and send a PR.

**Comment by chpio** [comment]
https://gist.github.com/chpio/51346658d18498e62ac55496b0e605d0 ?
you could add the selinux cfg files to that gist
